version: "3.8"
services:
  flask:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  vue:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    command: bun dev

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pixie
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
